name: Tofu Apply
on:
  push:
    branches: ["master"]
    paths:
      - "ch5/tofu/live/**"  # 🔥 Detect changes in any OpenTofu folder

jobs:
  detect-changes:
    name: "Detect Changes"
    runs-on: ubuntu-latest
    outputs:
      changed_folders: ${{ steps.filter.outputs.changed_folders }}
    steps:
      - uses: actions/checkout@v2

      - name: Detect changed OpenTofu folders
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            changed_folders:
              - "ch5/tofu/live/**"

  apply:
    name: "Tofu Apply"
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.changed_folders == 'true'
    strategy:
      matrix:
        folder: ${{ fromJson(needs.detect-changes.outputs.changed_folders) }}
    permissions:
      pull-requests: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::122610477635:role/lambda-sample-apply
          role-session-name: apply-${{ github.run_number }}-${{ github.actor }}
          aws-region: us-east-2

      - uses: opentofu/setup-opentofu@v1

      - name: tofu apply
        id: apply
        working-directory: ${{ matrix.folder }}
        run: |
          tofu init -no-color -input=false
          tofu apply -no-color -input=false -lock-timeout=60m -auto-approve

      - uses: jwalton/gh-find-current-pr@master
        id: find_pr
        with:
          state: all

      - uses: peter-evans/create-or-update-comment@v4
        if: steps.find_pr.outputs.number
        env:
          RESULT_EMOJI: ${{ steps.apply.outcome == 'success' && '✅' || '⚠️' }}
        with:
          issue-number: ${{ steps.find_pr.outputs.number }}
          body: |
            ## ${{ env.RESULT_EMOJI }} `tofu apply` output for `${{ matrix.folder }}`
            ```${{ steps.apply.outputs.stdout }}```
